config/routes.rb
WhatsUp::Application.routes.draw do
  resources :tweets,:only => [:index] do
	collection do
		post "pull_tweets"
	end
  end
  resources :alerts
  match 'alerts/refresh' => 'alerts#refresh'

  resources :events

  match '/syndication' => 'homepage#syndication'

  resources :events do
    collection do
      post 'pull_events'
    end
  end
  
  resources :articles do
    resources :comments, :only => [:create]
    collection do
      post 'pull_articles'
    end
  end
  root :to => "homepage#index"
  
  

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @tweets = Tweet.all
    @articles = Article.all.delete_if { |article| article.not_safe_for_work? }
    @events = Event.all
  end

  def syndication
    @items = (Article.all + Event.all).map(&:rss_data)
    @items.sort! { |a,b| b[:pubDate] <=> a[:pubDate] }

    respond_to do |format|
      format.rss { render :layout => false }
    end
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<div class="yui3-g">
<div id="articles" class="yui3-u-11-24">
  <h2><%= link_to 'Articles', articles_path %></h2>
  <% @articles.each do |a|  %>
  <div>
    <h3><%= link_to a.title, a %></h3>
    <div class="date"><%= a.date.to_s(:human) %></div>
    <p><%= a.content.humanize %></p>
  </div>
  <% end %>

</div>
<div id="tweets" class="yui3-u-11-24 float-right">
<% unless @tweets.empty? %>
  <h2><%= link_to 'Tweets', tweets_path %></h2>
<% end %>
<% @tweets.each do |t|  %>
  <div>
    <h3><%= link_to t.author, t.url %></h3>
    <div class="date"><%= t.date.to_s(:human) %></div>
    <p><%= t.content %></p>
  </div>
  <% end %>
</div>
</div>
<div class="yui3-g">

  <div id="events" class="yui3-u-11-24">
    <h2><%= link_to 'Events', events_path %></h2>
    <% @events.each do |e|  %>
    <div>
      <h3><%= link_to e.title, e %></h3>
      <div class="date"><%= e.date %></div>
      <p><%= e.description %></p>
    </div>
    <% end %>
  </div>
  <div class="yui3-u-11-24 float-right">
  </div>
</div>

<%= link_to "Articles and Events RSS", syndication_url(:format => 'rss') %>

app/views/homepage/syndication.rss.haml
!!! XML
%rss{:version => "2.0"}
  %channel
    %title What's up, y'all?
    %link= root_url
    %description A list of the most awesome stuff ever to happen near OSU
    %language en-us
    %pubDate= Time.now

    - for item in @items
      %item
        %title= item[:title]
        %description= item[:description]
        %pubDate= item[:pubDate]