config/routes.rb
WhatsUp::Application.routes.draw do
  resources :tweets,:only => [:index] do
	collection do
		post "pull_tweets"
	end
  end
  resources :alerts
  match 'alerts/refresh' => 'alerts#refresh'

  resources :events

  match '/syndication' => 'homepage#syndication'

  resources :events do
    collection do
      post 'pull_events'
    end
  end
  
  resources :articles do
    resources :comments, :only => [:create]
    collection do
      post 'pull_articles'
    end
  end
  root :to => "homepage#index"
  
  

end

app/models/article.rb
require 'open-uri'

class Article < ActiveRecord::Base
  has_many :comments
  
  validates_presence_of :title, :content, :date
  validate :unique_article

  PROFANITY = %w{ duck uofo hippies hippy }
  
  def unique_article
    articles = Article.where(:title => self.title, :content => self.content, :date => self.date).all
    articles.delete_if {|a| a.id == self.id}
    if articles.any?
      errors.add(:base, "Articles must be unique")
    end
  end

  def not_safe_for_work?
    for word in PROFANITY
      regex = /#{word}/i
      return true if title =~ regex
      return true if content =~ regex
    end
    return false
  end

  def Article.fetch_osu
    source_data = open('http://oregonstate.edu').read
    doc = Nokogiri::HTML(source_data)
    article_count = 0
    articles = doc.css('.news-story').each do |article|
      title = article.css('h3 a').text
      content = article.css('.teaser').text
      date = Date.parse(article.css('.date').text)
      Article.create(:title => title, :content => content, :date => date)
    end
  end

  # Stores a map of db field => RSS field
  RSS_FIELD_MAP = {
    :title => :title,
    :date => :pubDate,
    :content => :description
  }

  # Returns a hash of data suitable for RSS item output.  Data must include :title, :description, and :date
  def rss_data
    rss = {}
    for (db_field, rss_field) in RSS_FIELD_MAP
      rss[rss_field] = send(db_field)
    end

    return rss
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
  
  def pull_articles
    Article.fetch_osu
    redirect_to(articles_path, :notice => "Articles fetched")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.date %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

<br />
<br />
<%= form_tag pull_articles_articles_path %>
<%= submit_tag 'Fetch Articles From OSU' %>
</form>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Date:</b>
  <%= @article.date %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
<div class="comment">
<div class="comment_name"><i><%= comment.name %> @ <%= comment.created_at %></i></div>
<div class="comment_body"><%= comment.body %></div>
</div>
<% end %>

<h2>Add A Comment</h2>
<% form_for [@article, @article.comments.build] do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :body %>
  <%= f.text_area :body, :size => '30x5' %>
</p>

<p><%= f.submit 'Save' %></p>
<% end %>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>