config/routes.rb
WhatsUp::Application.routes.draw do
  resources :tweets,:only => [:index] do
	collection do
		post "pull_tweets"
	end
  end
  resources :alerts
  match 'alerts/refresh' => 'alerts#refresh'

  resources :events

  match '/syndication' => 'homepage#syndication'

  resources :events do
    collection do
      post 'pull_events'
    end
  end
  
  resources :articles do
    resources :comments, :only => [:create]
    collection do
      post 'pull_articles'
    end
  end
  root :to => "homepage#index"
  
  

end

app/models/event.rb
require 'open-uri'

class Event < ActiveRecord::Base
  validates_presence_of :title
  validate :unique_event

  def unique_event
    events = Event.where(:title => self.title, :description => self.description, :date => self.date).all
    events.delete_if {|e| e.id == self.id}
    if events.any?
      errors.add(:base, "Events must be unique")
    end
  end

  def Event.fetch_osu
    source_data = open('http://oregonstate.edu').read
    doc = Nokogiri::HTML(source_data)
    events = doc.css('.event').each do |event|
      title = event.css('h3 a').text
      description = event.css('.teaser').text
      date = Date.parse(event.css('.date .year').text + event.css('.date .month').text + event.css('.date .day').text )
      Event.create(:title => title, :description => description, :date => date)
    end
  end

  # Stores a map of db field => RSS field
  RSS_FIELD_MAP = {
    :title => :title,
    :date => :pubDate,
    :description => :description
  }

  # Returns a hash of data suitable for RSS item output.  Data must include :title, :description, and :date
  def rss_data
    rss = {}
    for (db_field, rss_field) in RSS_FIELD_MAP
      rss[rss_field] = send(db_field)
    end

    return rss
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
  
  def pull_events
    Event.fetch_osu
    redirect_to(Event, :notice => "Events fetched")
  end  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing events</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.date %></td>
    <td><%= event.title %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

<br />
<br />
<%= form_tag pull_events_events_path %>
<%= submit_tag 'Fetch Events From OSU' %>
</form>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>