config/routes.rb
WhatsUp::Application.routes.draw do
  resources :tweets,:only => [:index] do
	collection do
		post "pull_tweets"
	end
  end
  resources :alerts
  match 'alerts/refresh' => 'alerts#refresh'

  resources :events

  match '/syndication' => 'homepage#syndication'

  resources :events do
    collection do
      post 'pull_events'
    end
  end
  
  resources :articles do
    resources :comments, :only => [:create]
    collection do
      post 'pull_articles'
    end
  end
  root :to => "homepage#index"
  
  

end

app/models/alert.rb
require 'nokogiri'
require 'open-uri'

class Alert < ActiveRecord::Base
  validates_uniqueness_of :hash
  validates_presence_of :title, :hash, :date, :summary

  def self.parse(xml)
    doc = Nokogiri::XML(xml)
    alerts = doc.xpath('//methodResponse/params/param/value/struct/member')
    items = []
    alerts.each do |x|
      x = Nokogiri::XML(x.to_s)
      vals = {:hash => x.at_xpath('//name'),
              :title => x.at_xpath('//value/struct/member[name="title"]/value/string'),
              :summary => x.at_xpath('//value/struct/member[name="body"]/value/string'),
              :date => x.at_xpath('//value/struct/member[name="created"]/value/string')}
      not_nil = true
      vals.each do | key, value |
        not_nil = not_nil && !value.nil?
      end

      if not_nil
        vals.each do | key, value |
          vals[key] = value.text
        end
        vals[:date] = Time.at(vals[:date].to_i)
        items.push(vals)
      end
    end
    items
  end

  def self.fetch(url)
    self.parse(open(url))
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  # GET /alerts
  # GET /alerts.xml
  def index
    @alerts = Alert.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alerts }
    end
  end

  def refresh
    if params[:commit] == 'Refresh'
      new_alerts = Alert.fetch('http://oregonstate.edu/osuhomepage/data/alerts-1.xml');
      new_alerts.each do |x|
        begin
          Alert.create!(x)
        rescue
          nil
        end
      end
    end
    redirect_to :action => 'index'
  end

  # GET /alerts/1
  # GET /alerts/1.xml
  def show
    @alert = Alert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/new
  # GET /alerts/new.xml
  def new
    @alert = Alert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/1/edit
  def edit
    @alert = Alert.find(params[:id])
  end

  # POST /alerts
  # POST /alerts.xml
  def create
    @alert = Alert.new(params[:alert])

    respond_to do |format|
      if @alert.save
        format.html { redirect_to(@alert, :notice => 'Alert was successfully created.') }
        format.xml  { render :xml => @alert, :status => :created, :location => @alert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alerts/1
  # PUT /alerts/1.xml
  def update
    @alert = Alert.find(params[:id])

    respond_to do |format|
      if @alert.update_attributes(params[:alert])
        format.html { redirect_to(@alert, :notice => 'Alert was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.xml
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to(alerts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Listing alerts</h1>

<% form_for :alert, :url => { :action => 'refresh' } do |f| %>
  <%= f.submit :value => 'Refresh' %>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Summary</th>
  </tr>

<% @alerts.each do |alert| %>
  <tr>
    <td><%= alert.title %></td>
    <td><%= alert.date %></td>
    <td><%= alert.summary %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @alert.title %>
</p>

<p>
  <b>Date:</b>
  <%= @alert.date %>
</p>

<p>
  <b>Summary:</b>
  <%= @alert.summary %>
</p>


<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>